using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LeetcodeApp
{
    /// <summary>
    /// solution for  Find the Difference 389
    /// </summary>
    public class FindtheDifference
    {
        /*
            https://leetcode.com/problems/find-the-difference/
            Given two strings s and t which consist of only lowercase letters.

            String t is generated by random shuffling string s and then add one more letter at a random position.
            
            Find the letter that was added in t.
            
            Example:
            
            Input:
            s = "abcd"
            t = "abcde"
            
            Output:
            e
            
            Explanation:
            'e' is the letter that was added.
        */

        public static List<char> FindTheDifference(string s, string t)
        {
            char[] strS = s.ToArray();
            char[] strT = t.ToArray();

            Queue<char> queueS = new Queue<char>();
            foreach (char item in strS)
            {
                queueS.Enqueue(item);
            }

            Queue<char> queueT = new Queue<char>();
            foreach (char item in strT)
            {
                queueT.Enqueue(item);
            }

            List<char> result = new List<char>();

            while (queueS.Count > 0)
            {
                char c = queueS.Dequeue();

                char tDequeue = queueT.Dequeue();
                while (tDequeue != c)
                {
                    result.Add(tDequeue);
                    tDequeue = queueT.Dequeue();
                }
            }

            if (queueT.Count > 0)
            {
                result.Add(queueT.Dequeue());
            }

            return result;
        }
    }
}
